import './globals.css';

import type { Metadata } from 'next';

import { Inter } from 'next/font/google';

import QueryClientProvider from '../components/providers/query-client.provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  description: 'Generated by create turbo',
  title: 'Next Template',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryClientProvider>{children}</QueryClientProvider>
      </body>
    </html>
  );
}
