import './globals.css';

import type { Metadata } from 'next';

import { Analytics } from '@vercel/analytics/next';
import { SpeedInsights } from '@vercel/speed-insights/next';
import { Inter } from 'next/font/google';

import QueryClientProvider from '../components/providers/query-client.provider';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

export const metadata: Metadata = {
  applicationName: 'Next Template',
  authors: [
    {
      name: 'Hokki Suwanda',
      url: 'https://github.com/hokkyss',
    },
  ],
  description: 'Generated by create turbo',
  generator: 'Next.js',
  publisher: 'Vercel',
  title: 'Next Template',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.variable + ' ' + inter.className}>
        <QueryClientProvider>{children}</QueryClientProvider>
        <footer>
          <SpeedInsights />
          <Analytics />
        </footer>
      </body>
    </html>
  );
}
